version: '3'

silent: true

tasks:

  build000:
    desc: Builds the library in debug mode with settings 000
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  doc-open:
    desc: Generates the documentation and opens it in the browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc:
    desc: Generates the documentation
    cmds:
      - cmd: cargo doc --no-deps

  release:
    desc: Builds the library in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  test000:
    desc: Tests the library in debug mode
    cmds:
      - cmd: cargo test

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --all-targets

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo fmt

  targets:
    desc: Builds release version for multiple targets
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-gnu
      - cmd: cargo build --release --target=x86_64-unknown-linux-musl
      - cmd: cargo build --release --target=mips-unknown-linux-gnu
      - cmd: cargo build --release --target=wasm32-wasi
      - cmd: cargo build --release --target=wasm32-unknown-emscripten